### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by SirkoS** [ThomasPinna/python_zipfile_improvement#1]
I tested your code in a project on mine and I get ~10x improvement in my setup. So I would very much like to use it as a replacement for the native ZipFile in my scenario.

However, to actually use the code, however, it needs a proper license (preferably something like MIT). Could you please add that, so others can make use of the code and maybe even improve on it?

**Comment by ThomasPinna** [comment]
Hi SirkoS,

I'm glad my solution could help you get a performance increase. As you requested, I've added a license.

Greetings!
